### ISSUE TITLE
Need help with Lsp

### ISSUE THREAD

**Issue by ketgg** [dark-Jedi2108/nvide#1]
I get the following error, 

Spawning language server with cmd: `lua-language-server` failed. The language server is either not installed, missing from PATH, or not executable.

Do you know how I can fix this?

**Comment by namishh** [comment]
try adding `/home/<user>/.local/share/nvim/mason/bin` in your path, if you installed lua-language-server with Mason,
otherwise, install it with your package manager

**Comment by ketgg** [comment]
ok I have added it to my path, also have installed the language server using mason but the lsp doesn't work and dont see the lsp icon in statusline

**Comment by namishh** [comment]
whats the output of `:LspInfo`

**Comment by ketgg** [comment]
Below is the output of LspInfo, it was not there in command list when I did LspStart then it showed up
:LspInfo             |  No Lsp shown in statline and also its not working
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/105774228/214330942-f98f0ecb-40fd-48aa-a524-6b151871c52c.png)  |  ![](https://user-images.githubusercontent.com/105774228/214330957-9c63d59f-e6f8-40aa-85d2-715372581079.png)

Also when I press insert on any file I get the error maybe this is causing the issue
![Screenshot_20230124_203320](https://user-images.githubusercontent.com/105774228/214332409-f44bfef1-0bf3-46aa-8caa-29db6ce29d14.png)

In case of a Cpp file, I am still getting the above error but the LSP icon shows in the stat line but not working.

**Comment by ketgg** [comment]
Ok after restarting my terminal and nvim few times, Lsp is working now but these are the other issues I am facing:
1) I have to do `:LspStart` after nvim starts for one time, it doesn't start automatically when I press 'i' for insert
2) File Explorer doesn't change directory when I do `:cd <path>`, it shows the directory structure from where you have opened nvim in terminal

It would be great if you could help with this, thanks for your time :D

**Comment by namishh** [comment]
1. this should be fixed by @dharmx in the latest commit, so i recommend getting the latest version
2. i'll try and solve it , will lyk if i fix it

**Comment by namishh** [comment]
well @ryuJin25  i solved the second one too, but it's not perfect, the directory will change only after you open a file of a directory you cd'ed into.
`nnoremap <leader>cd :cd %:p:h<CR>:pwd<CR>`
this is the code,

i am gonna close this issue, feel free to reopen

**Comment by namishh** [comment]
yo @ryuJin25 was the problem solved?

**Comment by ketgg** [comment]
@chadcat5207 I got the latest version of your code lsp and all works fine but the statusbar doesn't show up
![Screenshot_20230129_221422](https://user-images.githubusercontent.com/105774228/215322384-6f3960f6-8feb-4a17-a75a-74b1283f8384.png)

**Comment by namishh** [comment]
so this is most likely due to the custom dash which is still a work in progress,
use the previous commit by
`git checkout -b 06c7400a035492b9ebb5ef02d10cb3a8ae9a4ebb`
and then run `nvim +PackerSync`

**Comment by ketgg** [comment]
alright thanks

**Comment by namishh** [comment]
@ryuJin25  did it work?

**Comment by ketgg** [comment]
nope i switched to some other previous commit then it worked

**Comment by ketgg** [comment]
btw when will the custom dash come out :D

**Comment by namishh** [comment]
> btw when will the custom dash come out :D

a lot of time, will update when i finish it
