### ISSUE TITLE
Create flake

### ISSUE THREAD

**Issue by hurricanehrndz** [dark-Jedi2108/nvide#4]
Checkout my [pdenv](https://github.com/hurricanehrndz/pdenv) that way this could be run via nix run

**Comment by namishh** [comment]
well i use nix but i am not quite good at it! so i will appreciate if you could make a pull request!

**Comment by hurricanehrndz** [comment]
I am okay, I have my own config. I only made the suggestion so that you could share the end result of your config with others that may have an interest.
